-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:cebba48f0ea6d1ae13f4e84c17ccd964:1/1$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "seal.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 136 },
				textureRect = { x = 2, y = 396, width = 100, height = 136 },
				spriteSourceSize = { width = 100, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smile.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 396, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smile_bigger.png",
				spriteColorRect = { x = 0, y = 8, width = 400, height = 392 },
				textureRect = { x = 2, y = 2, width = 400, height = 392 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zorder_test_-1.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 136 },
				textureRect = { x = 404, y = 278, width = 100, height = 136 },
				spriteSourceSize = { width = 100, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "zorder_test_0.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 136 },
				textureRect = { x = 404, y = 140, width = 100, height = 136 },
				spriteSourceSize = { width = 100, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "zorder_test_1.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 136 },
				textureRect = { x = 404, y = 2, width = 100, height = 136 },
				spriteSourceSize = { width = 100, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

